package country

internal val countryNames: Map<String, String> = mapOf(
    "AD" to "Andorra",
    "AE" to "United Arab Emirates",
    "AF" to "Afghanistan",
    "AG" to "Antigua and Barbuda",
    "AI" to "Anguilla",
    "AL" to "Albania",
    "AM" to "Armenia",
    "AO" to "Angola",
    "AQ" to "Antarctica",
    "AR" to "Argentina",
    "AS" to "American Samoa",
    "AT" to "Austria",
    "AU" to "Australia",
    "AW" to "Aruba",
    "AX" to "Åland Islands",
    "AZ" to "Azerbaijan",
    "BA" to "Bosnia and Herzegovina",
    "BB" to "Barbados",
    "BD" to "Bangladesh",
    "BE" to "Belgium",
    "BF" to "Burkina Faso",
    "BG" to "Bulgaria",
    "BH" to "Bahrain",
    "BI" to "Burundi",
    "BJ" to "Benin",
    "BL" to "Saint Barthélemy",
    "BM" to "Bermuda",
    "BN" to "Brunei Darussalam",
    "BO" to "Bolivia",
    "BR" to "Brazil",
    "BS" to "Bahamas",
    "BT" to "Bhutan",
    "BW" to "Botswana",
    "BY" to "Belarus",
    "BZ" to "Belize",
    "CA" to "Canada",
    "CC" to "Cocos (Keeling) Islands",
    "CD" to "Congo (the Democratic Republic of the)",
    "CF" to "Central African Republic",
    "CG" to "Congo",
    "CH" to "Switzerland",
    "CI" to "Côte d'Ivoire",
    "CK" to "Cook Islands",
    "CL" to "Chile",
    "CM" to "Cameroon",
    "CN" to "China",
    "CO" to "Colombia",
    "CR" to "Costa Rica",
    "CU" to "Cuba",
    "CV" to "Cabo Verde",
    "CW" to "Curaçao",
    "CX" to "Christmas Island",
    "CY" to "Cyprus",
    "CZ" to "Czechia",
    "DE" to "Germany",
    "DJ" to "Djibouti",
    "DK" to "Denmark",
    "DM" to "Dominica",
    "DO" to "Dominican Republic",
    "DZ" to "Algeria",
    "EC" to "Ecuador",
    "EE" to "Estonia",
    "EG" to "Egypt",
    "ER" to "Eritrea",
    "ES" to "Spain",
    "ET" to "Ethiopia",
    "FI" to "Finland",
    "FJ" to "Fiji",
    "FK" to "Falkland Islands (Malvinas)",
    "FM" to "Micronesia (Federated States of)",
    "FO" to "Faroe Islands",
    "FR" to "France",
    "GA" to "Gabon",
    "GB" to "United Kingdom of Great Britain and Northern Ireland",
    "GD" to "Grenada",
    "GE" to "Georgia",
    "GF" to "French Guiana",
    "GG" to "Guernsey",
    "GH" to "Ghana",
    "GI" to "Gibraltar",
    "GL" to "Greenland",
    "GM" to "Gambia",
    "GN" to "Guinea",
    "GP" to "Guadeloupe",
    "GQ" to "Equatorial Guinea",
    "GR" to "Greece",
    "GT" to "Guatemala",
    "GU" to "Guam",
    "GW" to "Guinea-Bissau",
    "GY" to "Guyana",
    "HK" to "Hong Kong",
    "HN" to "Honduras",
    "HR" to "Croatia",
    "HT" to "Haiti",
    "HU" to "Hungary",
    "ID" to "Indonesia",
    "IE" to "Ireland",
    "IL" to "Israel",
    "IM" to "Isle of Man",
    "IN" to "India",
    "IO" to "British Indian Ocean Territory",
    "IQ" to "Iraq",
    "IR" to "Iran (Islamic Republic of)",
    "IS" to "Iceland",
    "IT" to "Italy",
    "JE" to "Jersey",
    "JM" to "Jamaica",
    "JO" to "Jordan",
    "JP" to "Japan",
    "KE" to "Kenya",
    "KG" to "Kyrgyzstan",
    "KH" to "Cambodia",
    "KI" to "Kiribati",
    "KM" to "Comoros",
    "KN" to "Saint Kitts and Nevis",
    "KP" to "Korea (the Democratic People's Republic of)",
    "KR" to "Korea (the Republic of)",
    "KW" to "Kuwait",
    "KY" to "Cayman Islands",
    "KZ" to "Kazakhstan",
    "LA" to "Lao People's Democratic Republic",
    "LB" to "Lebanon",
    "LC" to "Saint Lucia",
    "LI" to "Liechtenstein",
    "LK" to "Sri Lanka",
    "LR" to "Liberia",
    "LS" to "Lesotho",
    "LT" to "Lithuania",
    "LU" to "Luxembourg",
    "LV" to "Latvia",
    "LY" to "Libya",
    "MA" to "Morocco",
    "MC" to "Monaco",
    "MD" to "Moldova (the Republic of)",
    "ME" to "Montenegro",
    "MF" to "Saint Martin (French part)",
    "MG" to "Madagascar",
    "MH" to "Marshall Islands",
    "MK" to "North Macedonia",
    "ML" to "Mali",
    "MM" to "Myanmar",
    "MN" to "Mongolia",
    "MO" to "Macao",
    "MP" to "Northern Mariana Islands",
    "MQ" to "Martinique",
    "MR" to "Mauritania",
    "MS" to "Montserrat",
    "MT" to "Malta",
    "MU" to "Mauritius",
    "MV" to "Maldives",
    "MW" to "Malawi",
    "MX" to "Mexico",
    "MY" to "Malaysia",
    "MZ" to "Mozambique",
    "NA" to "Namibia",
    "NC" to "New Caledonia",
    "NE" to "Niger",
    "NF" to "Norfolk Island",
    "NG" to "Nigeria",
    "NI" to "Nicaragua",
    "NL" to "Netherlands",
    "NO" to "Norway",
    "NP" to "Nepal",
    "NR" to "Nauru",
    "NU" to "Niue",
    "NZ" to "New Zealand",
    "OM" to "Oman",
    "PA" to "Panama",
    "PE" to "Peru",
    "PF" to "French Polynesia",
    "PG" to "Papua New Guinea",
    "PH" to "Philippines",
    "PK" to "Pakistan",
    "PL" to "Poland",
    "PM" to "Saint Pierre and Miquelon",
    "PN" to "Pitcairn",
    "PR" to "Puerto Rico",
    "PS" to "Palestine, State of",
    "PT" to "Portugal",
    "PW" to "Palau",
    "PY" to "Paraguay",
    "QA" to "Qatar",
    "RE" to "Réunion",
    "RO" to "Romania",
    "RS" to "Serbia",
    "RU" to "Russian Federation",
    "RW" to "Rwanda",
    "SA" to "Saudi Arabia",
    "SB" to "Solomon Islands",
    "SC" to "Seychelles",
    "SD" to "Sudan",
    "SE" to "Sweden",
    "SG" to "Singapore",
    "SH" to "Saint Helena, Ascension and Tristan da Cunha",
    "SI" to "Slovenia",
    "SK" to "Slovakia",
    "SL" to "Sierra Leone",
    "SM" to "San Marino",
    "SN" to "Senegal",
    "SO" to "Somalia",
    "SR" to "Suriname",
    "SS" to "South Sudan",
    "ST" to "Sao Tome and Principe",
    "SV" to "El Salvador",
    "SX" to "Sint Maarten (Dutch part)",
    "SY" to "Syrian Arab Republic",
    "SZ" to "Eswatini",
    "TC" to "Turks"
)